# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'promisekit-demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for promisekit-demo
  pod 'PromiseKit', '~> 6.0' # https://github.com/mxcl/PromiseKit

end
